export const song = {
  added_at: '2019-08-09T13:02:59Z',
  added_by: {
    external_urls: {
      spotify: 'https://open.spotify.com/user/dd912',
    },
    href: 'https://api.spotify.com/v1/users/dd912',
    id: 'dd912',
    type: 'user',
    uri: 'spotify:user:dd912',
  },
  is_local: false,
  primary_color: null,
  track: {
    album: {
      album_type: 'single',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2wY79sveU1sp5g7SokKOiI',
          },
          href: 'https://api.spotify.com/v1/artists/2wY79sveU1sp5g7SokKOiI',
          id: '2wY79sveU1sp5g7SokKOiI',
          name: 'Sam Smith',
          type: 'artist',
          uri: 'spotify:artist:2wY79sveU1sp5g7SokKOiI',
        },
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2cWZOOzeOm4WmBJRnD5R7I',
          },
          href: 'https://api.spotify.com/v1/artists/2cWZOOzeOm4WmBJRnD5R7I',
          id: '2cWZOOzeOm4WmBJRnD5R7I',
          name: 'Normani',
          type: 'artist',
          uri: 'spotify:artist:2cWZOOzeOm4WmBJRnD5R7I',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/1V9oE8bVilClrk5naqyyvL',
      },
      href: 'https://api.spotify.com/v1/albums/1V9oE8bVilClrk5naqyyvL',
      id: '1V9oE8bVilClrk5naqyyvL',
      images: [
        {
          height: 640,
          url:
            'https://i.scdn.co/image/f106fef8fa58a0b6c28f9fefb16c990a620f8337',
          width: 640,
        },
        {
          height: 300,
          url:
            'https://i.scdn.co/image/c79aee69bcfb5624468d58577037d450e5a1087d',
          width: 300,
        },
        {
          height: 64,
          url:
            'https://i.scdn.co/image/54d17aa803518c3941e24b3b80840f3bd8aa8547',
          width: 64,
        },
      ],
      name: 'Dancing With A Stranger (with Normani)',
      release_date: '2019-01-11',
      release_date_precision: 'day',
      total_tracks: 1,
      type: 'album',
      uri: 'spotify:album:1V9oE8bVilClrk5naqyyvL',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2wY79sveU1sp5g7SokKOiI',
        },
        href: 'https://api.spotify.com/v1/artists/2wY79sveU1sp5g7SokKOiI',
        id: '2wY79sveU1sp5g7SokKOiI',
        name: 'Sam Smith',
        type: 'artist',
        uri: 'spotify:artist:2wY79sveU1sp5g7SokKOiI',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2cWZOOzeOm4WmBJRnD5R7I',
        },
        href: 'https://api.spotify.com/v1/artists/2cWZOOzeOm4WmBJRnD5R7I',
        id: '2cWZOOzeOm4WmBJRnD5R7I',
        name: 'Normani',
        type: 'artist',
        uri: 'spotify:artist:2cWZOOzeOm4WmBJRnD5R7I',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AR',
      'AT',
      'AU',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KW',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'SA',
      'SE',
      'SG',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'US',
      'UY',
      'VN',
      'ZA',
    ],
    disc_number: 1,
    duration_ms: 171029,
    episode: false,
    explicit: false,
    external_ids: {
      isrc: 'GBUM71807386',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/6Qs4SXO9dwPj5GKvVOv8Ki',
    },
    href: 'https://api.spotify.com/v1/tracks/6Qs4SXO9dwPj5GKvVOv8Ki',
    id: '6Qs4SXO9dwPj5GKvVOv8Ki',
    is_local: false,
    name: 'Dancing With A Stranger (with Normani)',
    popularity: 87,
    preview_url:
      'https://p.scdn.co/mp3-preview/06f70639c8177c94fa50cb4deb89676007a7c7b9?cid=014b962707594a218d30b5e0052143eb',
    track: true,
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:6Qs4SXO9dwPj5GKvVOv8Ki',
  },
  video_thumbnail: {
    url: null,
  },
};

export const playlist = {
  collaborative: true,
  external_urls: {
    spotify: 'https: //open.spotify.com/playlist/7GRPR4fBbskJIzWHM9AHFM',
  },
  href: 'https: //api.spotify.com/v1/playlists/7GRPR4fBbskJIzWHM9AHFM',
  id: '7GRPR4fBbskJIzWHM9AHFM',
  images: [
    {
      height: 640,
      url:
        'https: //mosaic.scdn.co/640/92cfcd5e3940d9917c631f5f4f80db4f1424f8eabbba30213af9c7380245934492347ff6d03a95e2f106fef8fa58a0b6c28f9fefb16c990a620f8337f993bf17231f829bdeafed577b0354023a7db938',
      width: 640,
    },
    {
      height: 300,
      url:
        'https: //mosaic.scdn.co/300/92cfcd5e3940d9917c631f5f4f80db4f1424f8eabbba30213af9c7380245934492347ff6d03a95e2f106fef8fa58a0b6c28f9fefb16c990a620f8337f993bf17231f829bdeafed577b0354023a7db938',
      width: 300,
    },
    {
      height: 60,
      url:
        'https: //mosaic.scdn.co/60/92cfcd5e3940d9917c631f5f4f80db4f1424f8eabbba30213af9c7380245934492347ff6d03a95e2f106fef8fa58a0b6c28f9fefb16c990a620f8337f993bf17231f829bdeafed577b0354023a7db938',
      width: 60,
    },
  ],
  name: 'TraceCamp',
  owner: {
    display_name: 'dd912',
    external_urls: {
      spotify: 'https: //open.spotify.com/user/dd912',
    },
    href: 'https: //api.spotify.com/v1/users/dd912',
    id: 'dd912',
    type: 'user',
    uri: 'spotify:user:dd912',
  },
  primary_color: null,
  public: false,
  snapshot_id: 'MTk0LDc2NzBjMzE3NjI5ZjYzMTY5ZDE3N2QxOWM5YWI3OWU3Y2MyY2NkZjE=',
  tracks: {
    href: 'https: //api.spotify.com/v1/playlists/7GRPR4fBbskJIzWHM9AHFM/tracks',
    total: 143,
  },
  type: 'playlist',
  uri: 'spotify:playlist: 7GRPR4fBbskJIzWHM9AHFM',
};

export const user = {
  display_name: 'mohtendo64',
  external_urls: {
    spotify: 'https://open.spotify.com/user/mohtendo64',
  },
  followers: {
    href: null,
    total: 27,
  },
  href: 'https://api.spotify.com/v1/users/mohtendo64',
  id: 'mohtendo64',
  images: [
    {
      height: null,
      url:
        'https://profile-images.scdn.co/images/userprofile/default/33d5b90bc0e42ac0331ab0616f3695f292c43d66',
      width: null,
    },
  ],
  type: 'user',
  uri: 'spotify:user:mohtendo64',
};
